services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      DB_ENGINE: postgresql
      DB_NAME: mydb
      DB_USERNAME: postgres
      DB_PASS: strongpassword123
      DB_HOST: database-1.cz24aseke4o0.ap-south-1.rds.amazonaws.com
      DB_PORT: "5432"


